version: '2.2'
services:
  sevensenders:
    build:
      context: ./
      dockerfile: DockerFile
    image: sevensendersapi
    ports:
      - 8080:8080
    networks:
      - network1
    scale: 1

networks:
  network1: